### PR TITLE
Lotka–Volterra Equations

### PR DESCRIPTION
**Pull request by AndreyAPopov**
Also know as predator-prey.

### CODE REVIEW

**Comment by Steven-Roberts** [comment]
Looks ready to merge

**Comment by AndreyAPopov** [comment]
Should we add more presets before merging?

**Comment by Steven-Roberts** [comment]
I don't think so.  Different parameters will still lead to oscillatory dynamics.

**Comment by AndreyAPopov** [comment]
Added a "stable" preset which has the initial condition on the attractor, thus constant for all time.

**Pull request merged**
